name = "SeismicRayTrace"
uuid = "1a90cdcd-02e0-4887-85dc-4804a62d2cac"
authors = ["changguo1998 changguo1998@gmail.com"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
